"""Initial migration

Revision ID: 47c5ba165ca9
Revises: 
Create Date: 2024-05-28 20:50:31.050624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c5ba165ca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('customer_type', sa.Enum('USER', 'COMPANY', 'B2B_CUSTOMER', 'B2C_CUSTOMER', 'OTHER', name='CustomerTypeEnum'), nullable=True),
    sa.Column('industry', sa.Enum('USER', 'COMPANY', 'OTHER', name='IndustryEnum'), nullable=True),
    sa.Column('subIndustry', sa.Enum('USER', 'COMPANY', 'OTHER', name='IndustryEnum'), nullable=True),
    sa.Column('department', sa.Enum('USER', 'COMPANY', 'OTHER', name="<enum 'DepartmentEnum'>"), nullable=True),
    sa.Column('subDepartment', sa.Enum('USER', 'COMPANY', 'OTHER', name='DepartmentEnum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('module_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=True),
    sa.Column('kb', sa.Boolean(), nullable=True),
    sa.Column('call', sa.Boolean(), nullable=True),
    sa.Column('assistants', sa.Boolean(), nullable=True),
    sa.Column('chat_with_documents', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('oauth_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('oauth_token', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'OTHER', name='UserStatusEnum'), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('department', sa.Enum('USER', 'COMPANY', 'OTHER', name='UserStatusEnum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_role_id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=56), nullable=True),
    sa.Column('type', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', 'OTHER', name='ProcessedActionTypeEnum'), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('sms', sa.String(), nullable=True),
    sa.Column('webhook', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_type', sa.Enum('CHATGPT_4_0', 'LLAMA3', 'OTHER', name='LLMSEnum'), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('customer_key', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('base_plan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('module_profile_id', sa.Integer(), nullable=True),
    sa.Column('no_of_emails_per_day', sa.Integer(), nullable=True),
    sa.Column('no_of_emails_per_month', sa.Integer(), nullable=True),
    sa.Column('no_of_minutes_per_day', sa.Integer(), nullable=True),
    sa.Column('no_of_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('llms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('max_allowed_token', sa.Integer(), nullable=True),
    sa.Column('max_number_of_kb', sa.Integer(), nullable=True),
    sa.Column('max_number_of_action', sa.Integer(), nullable=True),
    sa.Column('assistants_daily_budget', sa.JSON(), nullable=True),
    sa.Column('max_no_assistants', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_profile_id'], ['module_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('subType', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('subStatus', sa.String(), nullable=True),
    sa.Column('leadSource', sa.String(), nullable=True),
    sa.Column('leadStatus', sa.String(), nullable=True),
    sa.Column('pipelineStatus', sa.String(), nullable=True),
    sa.Column('pipelineSubStatus', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('bpStatus', sa.String(), nullable=True),
    sa.Column('relationshipToCustomer', sa.String(), nullable=True),
    sa.Column('primaryAssignment', sa.String(), nullable=True),
    sa.Column('secondaryAssignment', sa.JSON(), nullable=True),
    sa.Column('subscriptionStatus', sa.String(), nullable=True),
    sa.Column('customFieldDropDown', sa.String(), nullable=True),
    sa.Column('customFieldPrice', sa.Float(), nullable=True),
    sa.Column('customFieldDates', sa.DateTime(), nullable=True),
    sa.Column('nextFollowUpDate', sa.DateTime(), nullable=True),
    sa.Column('customFields', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('fed_id', sa.String(), nullable=True),
    sa.Column('w9_form', sa.String(), nullable=True),
    sa.Column('irs', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notes_type', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('role_permission_map',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fags', sa.JSON(), nullable=True),
    sa.Column('model', sa.Enum('CHATGPT_4_0', 'LLAMA3', 'OTHER', name='LLMSEnum'), nullable=True),
    sa.Column('trained_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_meta_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('company_plan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('llms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('visibility_profile', sa.String(), nullable=True),
    sa.Column('assistant_daily_budget', sa.Float(), nullable=True),
    sa.Column('assistant_monthly_budget', sa.Float(), nullable=True),
    sa.Column('no_of_emails_per_month', sa.Integer(), nullable=True),
    sa.Column('no_of_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('no_of_emails_per_day', sa.Integer(), nullable=True),
    sa.Column('no_of_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('max_allowed_token', sa.Integer(), nullable=True),
    sa.Column('max_number_of_kb', sa.Integer(), nullable=True),
    sa.Column('max_number_of_action', sa.Integer(), nullable=True),
    sa.Column('max_no_assistants', sa.Integer(), nullable=True),
    sa.Column('plan_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('assistants_daily_budget', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('base_plan_id', sa.String(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['base_plan_id'], ['base_plan.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', name='RequestTypeEnum'), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('body_params', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('user_meta_data_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_meta_data_id'], ['user_meta_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paymentStatus', sa.Enum('PAID', 'PAYMENT_PENDING', 'CANCELLED', 'OTHER', name='InvoiceStatusEnum'), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('paymentMode', sa.Enum('UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'OTHER', name='PaymentModeEnum'), nullable=True),
    sa.Column('amountPaid', sa.Float(), nullable=True),
    sa.Column('invoice_created_at', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('invoiceType', sa.Enum('ANNUAL', 'QUARTERLY', 'OTHER', name='PlanTypeEnum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['company_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.String(length=255), nullable=True),
    sa.Column('user_plan_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('urls', sa.JSON(), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_plan_id'], ['company_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sent_email',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_template_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'QUEUED', 'DELIVERED', 'OPENED', 'CLICKED', name='EmailStatusEnum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['company_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_plan_usage_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no_of_emails_per_month', sa.Integer(), nullable=True),
    sa.Column('no_of_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('no_of_emails_per_day', sa.Integer(), nullable=True),
    sa.Column('no_of_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['company_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('assistants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('kb_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('SMS', 'EMAIL', 'VOICE', 'OTHER', name='AssistantTypeEnum'), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('synthesizer', sa.String(), nullable=True),
    sa.Column('enable_recordings', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_secret', sa.String(), nullable=True),
    sa.Column('intents', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('entities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keys', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.String(), nullable=True),
    sa.Column('jwt', sa.String(), nullable=True),
    sa.Column('incoming_call_greeting', sa.String(), nullable=True),
    sa.Column('outgoing_call_greeting', sa.String(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('project_details', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('ap_api_key', sa.String(), nullable=True),
    sa.Column('prompts', sa.JSON(), nullable=True),
    sa.Column('ai_type', sa.Enum('CHATGPT_4_0', 'LLAMA3', 'OTHER', name='llmsenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['company_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=True),
    sa.Column('from_', sa.String(length=255), nullable=True),
    sa.Column('to', sa.String(length=255), nullable=True),
    sa.Column('session_type', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=255), nullable=True),
    sa.Column('medium', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('session_started_at', sa.DateTime(), nullable=True),
    sa.Column('session_ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('session_cost', sa.Float(), nullable=True),
    sa.Column('session_state', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['company_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=True),
    sa.Column('conversation_uuid', sa.String(length=255), nullable=True),
    sa.Column('conversation_type', sa.Enum('USER', 'ASSISTANT', 'OTHER', name='ConversationTypeEnum'), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Text(), nullable=True),
    sa.Column('no_of_input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Text(), nullable=True),
    sa.Column('no_of_output_tokens', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('v_response', sa.JSON(), nullable=True),
    sa.Column('ai_thread_id', sa.String(length=255), nullable=True),
    sa.Column('ai_message_ids', sa.String(length=255), nullable=True),
    sa.Column('processed_action_id', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('intents', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('processed_actions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('action_id', sa.String(length=255), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', 'OTHER', name='processed_action_type_enum'), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('action_response', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['company_plan.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_actions')
    op.drop_table('conversations')
    op.drop_table('sessions')
    op.drop_table('assistants')
    op.drop_table('user_plan_usage_balance')
    op.drop_table('sent_email')
    op.drop_table('knowledge_base')
    op.drop_table('invoice')
    op.drop_table('requests')
    op.drop_table('company_plan')
    op.drop_table('user_meta_data')
    op.drop_table('training_data')
    op.drop_table('role_permission_map')
    op.drop_table('note')
    op.drop_table('email_templates')
    op.drop_table('customers')
    op.drop_table('base_plan')
    op.drop_table('api_keys')
    op.drop_table('actions')
    op.drop_table('user_role')
    op.drop_table('user')
    op.drop_table('permissions')
    op.drop_table('oauth_detail')
    op.drop_table('module_profile')
    op.drop_table('company')
    # ### end Alembic commands ###
