class Company(Base):
    __tablename__ = 'company'

    id = Column(String, primary_key=True, unique=True, nullable=False)
    company_name = Column(String, nullable=False)
    customer_name = Column(String)
    address = Column(String)
    phone = Column(String, nullable=False)
    website = Column(String)
    state = Column(String)
    city = Column(String)
    zip_code = Column(String)
    customer_type = Column(String, nullable=False)
    industry = Column(String, nullable=False)
    subIndustry = Column(String, nullable=False)
    department = Column(String, nullable=False)
    subDepartment = Column(String, nullable=False)
    created_at = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, nullable=False)
    user_plan = relationship('Company_plan', back_populates='company')
    notes = Column(JSON)
    fields = Column(JSON)
    knowledge_base = relationship('KnowledgeBase', back_populates='company')
    customers = relationship('Customer', back_populates='company')
    api_key = relationship('ApiKey', back_populates='company')
    user_roles = relationship('UserRole', back_populates='company')
    users = relationship('User', back_populates='company')
    actions = relationship('Action', back_populates='company')
    Training_data = relationship('Training_data', back_populates='company')
    email_templates = relationship('EmailTemplate', back_populates='company')